config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  resources :recipes
  
  get 'recipes/index'
  get 'recipes/show'
  get 'recipes/new'
  get 'recipes/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    mount_uploader :picture, PictureUploader
    validate :picture_size
    
    private
    
    #Validates the size of an uploaded picture.
    def picture_size
        if picture.size > 5.megabytes
            errors.add(:picture,"should be less than 5MB")
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  before_action :find_recipe,only:[:show, :edit, :update, :destroy]
  
  def index
    @recipe = Recipe.all.order("created_at DESC")
  end

  def show

  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    
    if @recipe.save
      flash[:sucsess] = 'recipe created'
      redirect_to @recipe
    else
      render:new
    end
  end
  
  def edit

  end
  
  def update
  
     
     if @recipe.update(recipe_params)
      flash[:sucsess] = 'recipe updated'
      redirect_to @recipe
    else
      render:edit
     end
  end
  
  def destroy
    
     @recipe.destroy
     flash[:sucsess] = 'recipe destroy'
     redirect_to root_path
  end
  
  private
  
  def recipe_params
    params.require(:recipe).permit(:title,:description,:picture,:picture_cache)
  end
  
  def find_recipe
   @recipe = Recipe.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type,message|%>
<div class = "alert alert-<%= message_type%>">
    <%= message %>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-brand">
        <%= link_to "Recipe Box", root_path %>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "New Recipe", new_recipe_path %></li>
            <li><%= link_to "Sign Out", root_path %></li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_message' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
        <div id="errors">
		<p><%= @recipe.errors.count %> Prevented this recipe from saving </p>
	</div>
	<% end %>
      <ul>
        <% @recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      </ul>
      <% end %>
    </div>

  <%= f.label :title %>
  <%= f.text_field :title %>
  
  <%= f.label :description %>
  <%= f.text_area :description %>
  
  <div class="field">
    <% if @recipe.picture? %>
      <div class="thumbnail">
        <%= image_tag @recipe.picture.url %>
      </div>
    <% end %><br>
    <%= f.label :picture %><br>
    <%= f.file_field :picture, accept: 'image/jpeg,image/git,image/png' %>
    <%= f.hidden_field :picture_cache %>
  </div>

<div class="field">
  <%= f.submit %>
<% end %>

<script type="text/javascript">
$('#picture_file').bind('change', function() {
  var size_in_megabytes = this.files[0].size/1024/1024;
  if (size_in_megabytes > 1) {
    alert('Maximum file size is 5MB. Please choose a smaller file.');
  }
});
</script>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render 'form'%>

app/views/recipes/index.html.erb
<h1>Recipes Box</h1>
<ul>
  <% @recipe.each do |recipe| %>
    <h2><%= link_to recipe.title, recipe %></h2>
  <% end %>
</ul>

app/views/recipes/new.html.erb
<div class="panel-header">
	<h1>New Recipe</h1>
</div>

<%= render 'form' %>
<%= link_to "Back", root_path, class: "btn btn-default" %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<p class="description"><%= @recipe.description %></p>
<% if @recipe.picture? %>
    <div class="thumbnail">
      <%= image_tag @recipe.picture.url %>
    </div>
  <% end %>
<p>Submitted by </p>

<%= link_to "Back", root_path, class: "btn btn-default" %>
<%= link_to "Edit", edit_recipe_path, class: "btn btn-default" %>
<%= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default" %>